// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgaJg-aWdIu1Ymf06TaEZYo_6AJY8GGT4',
    appId: '1:1083816701295:web:0fbdeccf49c8d6f52c4c9a',
    messagingSenderId: '1083816701295',
    projectId: 'hakko-c7bf7',
    authDomain: 'hakko-c7bf7.firebaseapp.com',
    databaseURL: 'https://hakko-c7bf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hakko-c7bf7.appspot.com',
    measurementId: 'G-MQXF33H54C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzYO3vC5V3-iu-xaeuOi8Kutovsdw0jU',
    appId: '1:1083816701295:android:88f1f8514fec0c452c4c9a',
    messagingSenderId: '1083816701295',
    projectId: 'hakko-c7bf7',
    databaseURL: 'https://hakko-c7bf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hakko-c7bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZCn7fAKtWzZ9xcegQ5-PAMtfFatGCuM',
    appId: '1:1083816701295:ios:a4b5b6a51b919b702c4c9a',
    messagingSenderId: '1083816701295',
    projectId: 'hakko-c7bf7',
    databaseURL: 'https://hakko-c7bf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hakko-c7bf7.appspot.com',
    iosBundleId: 'com.example.gazou',
  );
}
